In [2]:
import numpy as np

In [32]:
# Creating Arrays
arr0 = np.zeros(5)
arr1 = np.ones(5)
# arr => array([0., 0., 0., 0., 0.])
# type(arr[0]) => numpy.float64


# Using linspace
arr2 = np.linspace(2, 10, 9)
# arr2 => array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

a_list = [1, 2, 3, 4, 5, 6, 7, 8]
arr3 = np.array(a_list)
# arr3 => array([1, 2, 3, 4, 5, 6, 7, 8])
# arr3[0] => 1

b_list = [[1, 2, 3], [4, 5, 6]];
arr4 = np.array(b_list)
# arr4 => array([[1, 2, 3], [4, 5, 6]])
# arr4[1][0] => 4
# arr4.shape => (2, 3)

np.random.seed(0)
arr5 = np.random.randint(1, 100, size=6)
# arr5 => array([47, 89, 82, 38, 26, 78])
# arr5[-1] => 78
# arr5[0:2] => array([[47, 89]])

[45 48 65 68 68 10]
10


In [70]:
# Working with images
from skimage import io

# photo = io.imread('img1.jpg')
photo = io.imread('img2.png')
# type(photo) => numpy.ndarray
# photo.shape => (1280, 1920, 3) => rows, columns, color-space (3 for rgb)

import matplotlib.pyplot as plt
# plt.imshow(photo) => shows image
# plt.imshow(photo[::-1]) => Tilted image as rows are reversed
# plt.imshow(photo[:, ::-1]) => Mirror Image as columns are reversed
# plt.imshow(photo[400:1000, 100:1920]) => Cropping image
# plt.imshow(photo[::2, ::2]) => half the size of image as every other row and column are taken

# plt.imshow(photo)
# plt.imshow(photo[::12, ::12])
# print(np.sin(photo))


# More Functions
print(np.sum(photo))
print(np.prod(photo))
print(np.mean(photo))
print(np.std(photo))
print(np.var(photo))
print(np.min(photo))
print(np.max(photo))
print(np.argmin(photo))
print(np.argmax(photo))




197592654
0
188.43903923034668
96.55423762587642
9322.72080351421
0
255
3
0
[255 255 255   0]


In [91]:
# Some more numpy functions

myarr = np.array([1, 2, 3, 4, 5])
myarr1 = np.array([1, 2, 3, 4, 5, 6])
# myarr < 3 => array([ True,  True, False, False, False])
# myarr > 3 => array([False, False, False,  True,  True])
# myarr[myarr > 3] => array([4, 5]
# myarr[myarr <= 3] => array([1, 2, 3])


# photo_masked = np.where(photo > 70, 255, 0)
# plt.imshow(photo_masked)

# myarr + 30 => array([31, 32, 33, 34, 35])
# myarr - 30 => array([-29, -28, -27, -26, -25])
# myarr * myarr => array([ 1,  4,  9, 16, 25])
# myarr * myarr1 => ValueError: operands could not be broadcast together with shapes (5,) (6,) 
# myarr @ myarr => Dot product
# plt.imshow(photo[:,:,0].T) => transpose / Changes rows to columns

# myarr2 = np.array([3, 4, 1, 2, 5, 6])
# np.sort(myarr2)

array([1, 2, 3, 4, 5, 6])